### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by LenkaSedlackova** [faktaoklimatu/web-sk#52]
prehľad práce na jednotlivých branchoch

**Comment by LenkaSedlackova** [comment]
- [ ] scenar-transformacie-energetiky
*text hotový, chýba IG*
- [ ] svetove-dohody
*text hotový, chýba IG*
- [x] ETS #48 
*text hotový, chýbajú IG*
??? povolenky vs kvóty ???

- [x] 2020-sprava-transformacia-energetiky-do-2050 #49 
- [x] uholny-phaseout-eu #42 
- [x] preview-emisie-svet-na-osobu-hdp
- [x] mitigacne-opatrenia-mmf
2 rôzne branche (štúdia vs IG), vieme čo s tým, @mukrop?
*edit: texty hotové, treba dotiahnuť IG*
- [ ] 2020-reserse-transformacia-energetiky #44
*text skontrolovaný*
- [x] spoplatnenie-emisii-svet #53 
- [ ] explainers-emisie-vyroba-cementu
*chýba zdroj SK dát a grafiky*
- [x] vyvoj-cien-elektriny #56 
*chýba kus prekladu a dokončiť infografiku (obe súvisia s prevodom Kč na €)*

- [ ] emisie-fosilne-paliva
- [ ] emisne-intenzity
- [ ] emisie-eu-na-osobu
- [ ] emisie-eu
- [ ] emisie-vybrane-staty
- [ ] emisie-eu-poradie

**Comment by mukrop** [comment]
* `preview-ets` je len technicky branch zodpovedajuci `ETS`, ten netreba riesit samostatne
* `mitigacne-opatrenia-mmf` je ten konflitny branch, ktory som spominal v #43. Infografika aj studia k MMF uz su zverejnene, ale je tam este `spoplatnenie-emisii-svet`, ktore nemam prehlad, ci je aj inde.

**Comment by LenkaSedlackova** [comment]
@vrq-github , prosím oprav ešte [infografiku Spoplatnenia emisií](https://github.com/faktaoklimatu/web-sk/blob/mitigacne-opatrenia-mmf/_infographics/opatrenia/spoplatnenie-emisi-svet.pdf) a neviem, čo je s [touto k MMF](https://github.com/faktaoklimatu/web-sk/blob/mitigacne-opatrenia-mmf/_infographics/opatrenia/mitigacne-opatrenia-mmf.pdf), ukazuje sa mi blank page 
![image](https://user-images.githubusercontent.com/56084968/140884772-41fb6c5e-2338-40b8-99ad-9c3a520c09a3.png)

**Comment by mukrop** [comment]
Zatvaram, pretoze branche je treba aj tak na novo premigrovat (v medzicase sa zmenil system), takze sa to vysklada znova.
